### ISSUE TITLE
Example won't compile: ! Package PGF Math Error: Unknown function `input' (in 'input').

### ISSUE THREAD

**Issue by typorian** [peer23peer/PIDcircuitTikZ#12]
When I try to compile the example I get the following errors:

`! Package PGF Math Error: Unknown function `input' (in 'input').`

`! Package PGF Math Error: Unknown function `output' (in 'output').`

`! Package PGF Math Error: Unknown function `refrigerant' (in 'refrigerant in').`

is this an issue with my installation? I tried installing it both globally and locally. All packages are up to date.

**Comment by jellespijker** [comment]
Hi Typorian,

Can you create an issue at https://gitlab.com/jellespijker/PIDcircuitTikZ/issues  

This is just a mirror repo.

P.S. try to compile `PIDcircuitTikZ.tex` because the `example.tex` file might be a remnant which I forget to remove.
